influxdb:
  host: 172.30.1.140
  port: 8086
  username: influx
  password: influx
  db_name: telegraf

mariadb:
  host: 172.30.1.140
  port: 3306
  username: prefect
  password: prefect
  db_name: prefect_metric_watcher

postgresql:
  host: 172.30.1.140
  port: 5432
  username: prefect
  password: prefect
  db_name: prefect